import { FormEvent, useState } from "react";
import "./auth.css";

type Branding={appName:string;companyName:string};
export function AuthScreen({ branding,needsBootstrap, onAuthenticated }: {branding:Branding;needsBootstrap: boolean | null; onAuthenticated: (token: string) => void }) {
  const [form, setForm] = useState({ fullName: "", username: "", password: "" });
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setMessage(""); try { const response = await fetch(needsBootstrap ? "/api/auth/bootstrap" : "/api/auth/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const contentType = response.headers.get("content-type") ?? ""; if (!contentType.includes("application/json")) throw new Error("Server API tidak merespons dengan benar. Pastikan backend terbaru sedang berjalan."); const body = await response.json(); if (!response.ok) throw new Error(body.message); onAuthenticated(body.token); } catch (error) { setMessage(error instanceof Error ? error.message : "Autentikasi gagal."); } finally { setLoading(false); } }
  if (needsBootstrap === null) return <div className="auth-page"><div className="auth-card"><p>Memeriksa konfigurasi ERP...</p></div></div>;
  return <div className="auth-page"><div className="auth-brand"><span>{branding.appName.charAt(0).toUpperCase()||"E"}</span> {branding.appName}</div><form className="auth-card" onSubmit={submit}><div className="auth-icon">⌁</div><h1>{needsBootstrap ? `Buat Administrator ${branding.appName}` : `Masuk ke ${branding.appName}`}</h1><p>{needsBootstrap ? `Siapkan akun pertama ${branding.companyName} untuk mengelola sistem.` : `Gunakan akun ${branding.appName} Anda untuk melanjutkan.`}</p>{needsBootstrap && <label>Nama lengkap<input value={form.fullName} onChange={(e)=>setForm({...form,fullName:e.target.value})} minLength={3} required /></label>}<label>Username<input value={form.username} onChange={(e)=>setForm({...form,username:e.target.value})} minLength={3} autoComplete="username" required /></label><label>Password<input type="password" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} minLength={8} autoComplete={needsBootstrap ? "new-password" : "current-password"} required /></label>{message && <div className="auth-error">{message}</div>}<button className="primary-button" disabled={loading}>{loading ? "Memproses..." : needsBootstrap ? "Buat akun & masuk" : "Masuk"}</button></form></div>;
}
