import type { FormEvent } from "react";

type Config = { server: string; database: string; user: string; encrypt: boolean; trustServerCertificate: boolean };
type Props = { config: Config; password: string; testing: boolean; result: { kind: "success" | "error"; message: string } | null; onPassword: (value: string) => void; onConfig: (key: keyof Config, value: string | boolean) => void; onSubmit: (event: FormEvent) => void };

export function DatabaseSettings({ config, password, testing, result, onPassword, onConfig, onSubmit }: Props) {
  const command = `sqlcmd -S "${config.server || "tcp:PUBLIC_IP,1433"}" -d ${config.database || "erp"} -U ${config.user || "sqlserver"} -C`;
  return <div className="settings-layout"><section><div className="welcome compact"><div><h2>Pengaturan Sistem</h2><p>Kelola koneksi SQL Server untuk ERP.</p></div></div><div className="settings-tabs"><button className="tab active">Koneksi Database</button><button className="tab">Profil Perusahaan</button><button className="tab">Notifikasi</button></div><form className="panel connection-panel" onSubmit={onSubmit}><div className="connection-heading"><div className="db-symbol">▤</div><div><h3>Microsoft SQL Server</h3><p>Gunakan format koneksi yang sama seperti sqlcmd.</p></div><span className="environment">SQLCMD</span></div><div className="connection-example">{command}</div><div className="form-grid"><label className="full">Server (-S)<input value={config.server} onChange={(event) => onConfig("server", event.target.value)} placeholder="tcp:PUBLIC_IP,1433" pattern="tcp:[^,]+,[0-9]+" required /></label><label>Database (-d)<input value={config.database} onChange={(event) => onConfig("database", event.target.value)} placeholder="erp" required /></label><label>Username (-U)<input value={config.user} onChange={(event) => onConfig("user", event.target.value)} placeholder="sqlserver" required /></label><label className="full">Password<input type="password" value={password} onChange={(event) => onPassword(event.target.value)} placeholder="Masukkan password SQL Server" autoComplete="current-password" required /></label></div><div className="switch-row"><label className="switch-label"><input type="checkbox" checked={config.encrypt} onChange={(event) => onConfig("encrypt", event.target.checked)} /><span className="switch" />Enkripsi koneksi</label><label className="switch-label"><input type="checkbox" checked={config.trustServerCertificate} onChange={(event) => onConfig("trustServerCertificate", event.target.checked)} /><span className="switch" />Percayai sertifikat server (-C)</label></div>{result && <div className={`connection-result ${result.kind}`}>{result.kind === "success" ? "✓" : "!"}<span>{result.message}</span></div>}<div className="form-actions"><p>🔒 Disimpan hanya setelah koneksi berhasil.</p><button className="primary-button" type="submit" disabled={testing}>{testing ? "Menguji koneksi..." : "Uji & Simpan Koneksi"}</button></div></form></section><aside className="settings-side"><article className="panel"><h3>Format koneksi</h3><ol><li>Server: tcp:IP,PORT</li><li>Database sesuai parameter -d.</li><li>Username sesuai parameter -U.</li><li>-C berarti percaya sertifikat.</li></ol></article><article className="security-note"><span>⌁</span><div><strong>Dapat diedit kembali</strong><p>Ubah nilainya lalu uji ulang sebelum konfigurasi baru disimpan.</p></div></article></aside></div>;
}
