import { FormEvent, useEffect, useState } from "react";

type Config = { server: string; database: string; user: string; encrypt: boolean; trustServerCertificate: boolean };
type Branding = { appName: string; companyName: string };
type Result = { kind: "success" | "error"; message: string } | null;
type Props = {
  token:string; branding:Branding; onBrandingSaved:(branding:Branding)=>void;
  config: Config; password: string; testing: boolean; result: Result;
  onPassword: (value: string) => void;
  onConfig: (key: keyof Config, value: string | boolean) => void;
  onSubmit: (event: FormEvent) => void;
};

export function DatabaseSettings({ token,branding,onBrandingSaved,config,password,testing,result,onPassword,onConfig,onSubmit }: Props) {
  const [tab,setTab]=useState<"database"|"branding">("database");
  const [identity,setIdentity]=useState(branding); const [saving,setSaving]=useState(false); const [identityResult,setIdentityResult]=useState<Result>(null);
  useEffect(()=>setIdentity(branding),[branding]);
  const command = `sqlcmd -S "${config.server || "tcp:PUBLIC_IP,1433"}" -d ${config.database || "erp"} -U ${config.user || "sqlserver"} -C`;
  async function saveIdentity(event:FormEvent){event.preventDefault();setSaving(true);setIdentityResult(null);try{const response=await fetch("/api/settings/branding",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(identity)});const body=await response.json();if(!response.ok)throw new Error(body.message);onBrandingSaved(body.branding);setIdentityResult({kind:"success",message:body.message});}catch(error){setIdentityResult({kind:"error",message:error instanceof Error?error.message:"Identitas gagal disimpan."});}finally{setSaving(false);}}

  return <div className="settings-layout"><section><div className="welcome compact"><div><h2>Pengaturan Sistem</h2><p>Kelola identitas aplikasi dan koneksi SQL Server.</p></div></div>
    <div className="settings-tabs"><button type="button" className={`tab ${tab==="database"?"active":""}`} onClick={()=>setTab("database")}>Koneksi Database</button><button type="button" className={`tab ${tab==="branding"?"active":""}`} onClick={()=>setTab("branding")}>Profil Perusahaan</button></div>
    {tab==="database"?<form className="panel connection-panel" onSubmit={onSubmit}><div className="connection-heading"><div className="db-symbol">▤</div><div><h3>Microsoft SQL Server</h3><p>Gunakan format koneksi yang sama seperti sqlcmd.</p></div><span className="environment">SQLCMD</span></div><div className="connection-example">{command}</div><div className="form-grid"><label className="full">Server (-S)<input value={config.server} onChange={(event) => onConfig("server", event.target.value)} placeholder="tcp:PUBLIC_IP,1433" pattern="tcp:[^,]+,[0-9]+" required /></label><label>Database (-d)<input value={config.database} onChange={(event) => onConfig("database", event.target.value)} placeholder="erp" required /></label><label>Username (-U)<input value={config.user} onChange={(event) => onConfig("user", event.target.value)} placeholder="sqlserver" required /></label><label className="full">Password<input type="password" value={password} onChange={(event) => onPassword(event.target.value)} placeholder="Masukkan password SQL Server" autoComplete="current-password" required /></label></div><div className="switch-row"><label className="switch-label"><input type="checkbox" checked={config.encrypt} onChange={(event) => onConfig("encrypt", event.target.checked)} /><span className="switch" />Enkripsi koneksi</label><label className="switch-label"><input type="checkbox" checked={config.trustServerCertificate} onChange={(event) => onConfig("trustServerCertificate", event.target.checked)} /><span className="switch" />Percayai sertifikat server (-C)</label></div>{result && <div className={`connection-result ${result.kind}`}>{result.kind === "success" ? "✓" : "!"}<span>{result.message}</span></div>}<div className="form-actions"><p>🔒 Disimpan hanya setelah koneksi berhasil.</p><button className="primary-button" type="submit" disabled={testing}>{testing ? "Menguji koneksi..." : "Uji & Simpan Koneksi"}</button></div></form>
    :<form className="panel connection-panel" onSubmit={saveIdentity}><div className="connection-heading"><div className="db-symbol">{identity.appName.charAt(0).toUpperCase()||"E"}</div><div><h3>Identitas aplikasi</h3><p>Nama ini tampil di login, dashboard, judul browser, PDF, dan Excel.</p></div><span className="environment">CUSTOM</span></div><div className="form-grid"><label>Nama ERP<input value={identity.appName} onChange={(event)=>setIdentity({...identity,appName:event.target.value})} minLength={2} maxLength={40} placeholder="ERPJIN" required /></label><label>Nama Perusahaan<input value={identity.companyName} onChange={(event)=>setIdentity({...identity,companyName:event.target.value})} minLength={2} maxLength={120} placeholder="PT Hajijin Amri" required /></label></div>{identityResult&&<div className={`connection-result ${identityResult.kind}`}>{identityResult.kind==="success"?"✓":"!"}<span>{identityResult.message}</span></div>}<div className="identity-preview"><span>{identity.appName.charAt(0).toUpperCase()||"E"}</span><div><strong>{identity.appName||"Nama ERP"}</strong><small>{identity.companyName||"Nama perusahaan"}</small></div></div><div className="form-actions"><p>Perubahan disimpan pada database SQL yang sedang aktif.</p><button className="primary-button" type="submit" disabled={saving}>{saving?"Menyimpan...":"Simpan Identitas"}</button></div></form>}
  </section><aside className="settings-side"><article className="panel"><h3>{tab==="database"?"Format koneksi":"Cakupan perubahan"}</h3>{tab==="database"?<ol><li>Server: tcp:IP,PORT</li><li>Database sesuai parameter -d.</li><li>Username sesuai parameter -U.</li><li>-C berarti percaya sertifikat.</li></ol>:<ol><li>Layar koneksi dan login.</li><li>Sidebar dan judul browser.</li><li>Header PDF dan Excel.</li><li>Tersimpan per database.</li></ol>}</article><article className="security-note"><span>⌁</span><div><strong>{tab==="database"?"Dapat diedit kembali":"Identitas per database"}</strong><p>{tab==="database"?"Ubah nilainya lalu uji ulang sebelum konfigurasi baru disimpan.":"Jika koneksi berpindah ke SQL B, aplikasi memakai identitas yang tersimpan pada SQL B."}</p></div></article></aside></div>;
}
